cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'git'
brew 'coreutils' # gnu coreutils
brew 'curl'
brew 'wget'

brew 'cocoapods'
brew 'mas' # mac app store
brew 'the_silver_searcher' # ack on steroids
brew 'asdf' # version manager for everything
brew 'bat' # cat on steroids
brew 'tldr'
brew 'neovim'
brew 'gh'
brew 'terminal-notifier'
brew 'diff-so-fancy'
brew 'wifi-password'
brew 'tmux'
brew 'exa'
brew 'git-extras'
brew 'fasd'
brew 'fd'
brew 'delta'
brew 'fzf' # fuzzy finder
brew 'gpg'
brew 'gpg2'
brew 'jq' # json query
brew 'readline'
brew 'watchman'
brew 'yq' # like jq, for yaml

cask 'brave-browser'
cask '1password'
cask 'dozer'
cask 'hazeover'
cask 'iterm2'
cask 'visual-studio-code'
cask 'qlcolorcode'
cask 'quicklook-json'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-source-code-pro'